#!/bin/bash

folder="$1"

process_file() {
  local country_name="$1"
  local iso2=""

  case "$country_name" in
    "albania") iso2="al" ;;
    "algeria") iso2="dz" ;;
    "american-samoa") iso2="as" ;;
    "andorra") iso2="ad" ;;
    "anguilla") iso2="ai" ;;
    "antigua-and-barbuda") iso2="ag" ;;
    "argentina") iso2="ar" ;;
    "au-torres-strait-islands") iso2="au-tsi" ;;
    "australia") iso2="au" ;;
    "australia-act") iso2="au-act" ;;
    "australia-nt") iso2="au-nt" ;;
    "australia-tas") iso2="au-tas" ;;
    "australia-nsw") iso2="au-nsw" ;;
    "turks-and-caicos-islands") iso2="tc" ;;
    "eswatini") iso2="sz" ;;
    "central-african-republi") iso2="cf" ;;
    "mauritius") iso2="mu" ;;
    "tuvalu") iso2="tv" ;;
    "austria") iso2="at" ;;
    "azerbaijan") iso2="az" ;;
    "belarus") iso2="by" ;;
    "belgium") iso2="be" ;;
    "benin") iso2="bj" ;;
    "bermuda") iso2="bm" ;;
    "bhutan") iso2="bt" ;;
    "bolivia") iso2="bo" ;;
    "bosnia-and-herzegovina") iso2="ba" ;;
    "botswana") iso2="bw" ;;
    "brazil") iso2="br" ;;
    "bulgaria") iso2="bg" ;;
    "burkina-faso") iso2="bf" ;;
    "burundi") iso2="bi" ;;
    "cameroon") iso2="cm" ;;
    "canada") iso2="ca" ;;
    "canada-bc") iso2="ca-bc" ;;
    "cayman-islands") iso2="ky" ;;
    "chile") iso2="cl" ;;
    "china") iso2="cn" ;;
    "christmas-island") iso2="cx" ;;
    "comoros") iso2="km" ;;
    "costa-rica") iso2="cr" ;;
    "cyprus") iso2="cy" ;;
    "czechia") iso2="cz" ;;
    "denmark") iso2="dk" ;;
    "dominican-republic") iso2="do" ;;
    "ecuador") iso2="ec" ;;
    "ecuador-w") iso2="ec-w" ;;
    "martinique") iso2="mq" ;;
    "myanmar") iso2="mm" ;;
    "egypt") iso2="eg" ;;
    "equatorial-guinea") iso2="gq" ;;
    "ethiopia") iso2="et" ;;
    "ethiopia-sw") iso2="et-sw" ;;
    "ethiopia-sn") iso2="et-sn" ;;
    "ethiopia-so") iso2="et-so" ;;
    "ethiopia-ha") iso2="et-ha" ;;
    "republic-of-the-congo") iso2="cg" ;;
    "french-polynesia") iso2="pf" ;;
    "finland") iso2="fi" ;;
    "france") iso2="fr" ;;
    "france-bre") iso2="fr-br" ;;
    "french-southern-territories") iso2="tf" ;;
    "gambia") iso2="gm" ;;
    "georgia") iso2="ge" ;;
    "germany") iso2="de" ;;
    "ghana") iso2="gh" ;;
    "gibraltar") iso2="gi" ;;
    "greece") iso2="gr" ;;
    "grenada") iso2="gd" ;;
    "guam") iso2="gu" ;;
    "guyana") iso2="gy" ;;
    "haiti") iso2="ht" ;;
    "hong-kong") iso2="hk" ;;
    "india") iso2="in" ;;
    "india-gj") iso2="in-gj" ;;
    "india-ka") iso2="in-ka" ;;
    "indonesia") iso2="id" ;;
    "indonesia-jb") iso2="id-jb" ;;
    "iraq") iso2="iq" ;;
    "iraq-kr") iso2="iq-kr" ;;
    "ireland") iso2="ie" ;;
    "isle-of-man") iso2="im" ;;
    "israel") iso2="il" ;;
    "italy") iso2="it" ;;
    "italy-42") iso2="it-42" ;;
    "italy-45") iso2="it-45" ;;
    "italy-52") iso2="it-52" ;;
    "italy-55") iso2="it-55" ;;
    "italy-57") iso2="it-57" ;;
    "italy-62") iso2="it-62" ;;
    "italy-65") iso2="it-65" ;;
    "italy-67") iso2="it-67" ;;
    "italy-72") iso2="it-72" ;;
    "italy-75") iso2="it-75" ;;
    "italy-77") iso2="it-77" ;;
    "italy-78") iso2="it-78" ;;
    "italy-82") iso2="it-82" ;;
    "italy-88") iso2="it-88" ;;
    "kazakhstan") iso2="kz" ;;
    "kuwait") iso2="kw" ;;
    "latvia") iso2="lv" ;;
    "lebanon") iso2="lb" ;;
    "libya") iso2="ly" ;;
    "lithuania") iso2="lt" ;;
    "macao") iso2="mo" ;;
    "madagascar") iso2="mg" ;;
    "malaysia") iso2="my" ;;
    "maldives") iso2="mv" ;;
    "malta") iso2="mt" ;;
    "mauritania") iso2="mr" ;;
    "mayotte") iso2="yt" ;;
    "mexico") iso2="mx" ;;
    "micronesia") iso2="fm" ;;
    "moldova") iso2="md" ;;
    "monaco") iso2="mc" ;;
    "montenegro") iso2="me" ;;
    "montserrat") iso2="ms" ;;
    "morocco") iso2="ma" ;;
    "mozambique") iso2="mz" ;;
    "nauru") iso2="nr" ;;
    "nepal") iso2="np" ;;
    "netherlands-antilles") iso2="an" ;;
    "netherlands-fr") iso2="nl-fr" ;;
    "nicaragua") iso2="ni" ;;
    "nigeria") iso2="ng" ;;
    "north-korea") iso2="kp" ;;
    "north-macedonia") iso2="mk" ;;
    "northern-cyprus") iso2="cy" ;;
    "northern-mariana-islands") iso2="mp" ;;
    "norway") iso2="no" ;;
    "oman") iso2="om" ;;
    "pakistan") iso2="pk" ;;
    "pakistan-sd") iso2="pk-sd" ;;
    "pakistan-jk") iso2="pk-jk" ;;
    "panama") iso2="pa" ;;
    "papua-new-guinea") iso2="pg" ;;
    "peru") iso2="pe" ;;
    "philippines") iso2="ph" ;;
    "pitcairn-islands") iso2="pn" ;;
    "poland") iso2="pl" ;;
    "portugal") iso2="pt" ;;
    "puerto-rico") iso2="pr" ;;
    "qatar") iso2="qa" ;;
    "reunion") iso2="re" ;;
    "romania") iso2="ro" ;;
    "russia") iso2="ru" ;;
    "russia-ba") iso2="ru-ba" ;;
    "russia-ce") iso2="ru-ce" ;;
    "russia-dpr") iso2="ru-dpr" ;;
    "russia-lpr") iso2="ru-lpr" ;;
    "russia-ta") iso2="ru-ta" ;;
    "russia-ud") iso2="ru-ud" ;;
    "rwanda") iso2="rw" ;;
    "saint-barthelemy") iso2="bl" ;;
    "saint-kitts-and-nevis") iso2="kn" ;;
    "senegal") iso2="sn" ;;
    "serbia") iso2="rs" ;;
    "seychelles") iso2="sc" ;;
    "sierra-leone") iso2="sl" ;;
    "singapore") iso2="sg" ;;
    "slovakia") iso2="sk" ;;
    "slovenia") iso2="si" ;;
    "solomon-islands") iso2="sb" ;;
    "somalia") iso2="so" ;;
    "south-korea") iso2="kr" ;;
    "spain") iso2="es" ;;
    "spain-pv") iso2="es" ;;
    "spain-galicia") iso2="es-ga" ;;
    "spain-ib") iso2="es-ib" ;;
    "gabon") iso2="ga" ;;
    "south-africa") iso2="za" ;;
    "luxembourg") iso2="lu" ;;
    "paraguay") iso2="py" ;;
    "sudan") iso2="sd" ;;
    "sweden") iso2="se" ;;
    "switzerland") iso2="ch" ;;
    "syria") iso2="sy" ;;
    "taiwan") iso2="tw" ;;
    "thailand") iso2="th" ;;
    "timor-leste") iso2="tl" ;;
    "togo") iso2="tg" ;;
    "tokelau") iso2="tk" ;;
    "tonga") iso2="to" ;;
    "trinidad-and-tobago") iso2="tt" ;;
    "tristan-da-cunha") iso2="sh-ta" ;;
    "turkey") iso2="tr" ;;
    "turkmenistan") iso2="tm" ;;
    "uk-cornwall") iso2="gb-cw" ;;
    "uk-england") iso2="gb-eng" ;;
    "uk-northern-ireland") iso2="gb-nir" ;;
    "uk-scotland") iso2="gb-sct" ;;
    "uk-wales") iso2="gb-wls" ;;
    "ukraine") iso2="ua" ;;
    "united-states") iso2="us" ;;
    "uruguay") iso2="uy" ;;
    "us-alaska") iso2="us-ak" ;;
    "us-arizona") iso2="us-az" ;;
    "us-arkansas") iso2="us-ar" ;;
    "us-betsy-ross") iso2="us-br" ;;
    "us-california") iso2="us-ca" ;;
    "us-colorado") iso2="us-co" ;;
    "us-connecticut") iso2="us-ct" ;;
    "us-delaware") iso2="us-de" ;;
    "us-florida") iso2="us-fl" ;;
    "us-georgia") iso2="us-ga" ;;
    "us-hawaii") iso2="us-hi" ;;
    "us-idaho") iso2="us-id" ;;
    "us-illinois") iso2="us-il" ;;
    "us-indiana") iso2="us-in" ;;
    "us-iowa") iso2="us-ia" ;;
    "us-kansas") iso2="us-ks" ;;
    "us-kentucky") iso2="us-ky" ;;
    "us-louisiana") iso2="us-la" ;;
    "us-maine") iso2="us-me" ;;
    "us-maryland") iso2="us-md" ;;
    "us-massachusetts") iso2="us-ma" ;;
    "us-michigan") iso2="us-mi" ;;
    "us-minnesota") iso2="us-mn" ;;
    "us-mississippi") iso2="us-ms" ;;
    "us-missouri") iso2="us-mo" ;;
    "us-montana") iso2="us-mt" ;;
    "us-nebraska") iso2="us-ne" ;;
    "us-nevada") iso2="us-nv" ;;
    "us-new-hampshire") iso2="us-nh" ;;
    "us-new-jersey") iso2="us-nj" ;;
    "us-new-mexico") iso2="us-nm" ;;
    "us-new-york") iso2="us-ny" ;;
    "us-north-carolina") iso2="us-nc" ;;
    "us-north-dakota") iso2="us-nd" ;;
    "us-ohio") iso2="us-oh" ;;
    "us-oklahoma") iso2="us-ok" ;;
    "us-oregon") iso2="us-or" ;;
    "us-pennsylvania") iso2="us-pa" ;;
    "us-rhode-island") iso2="us-ri" ;;
    "us-south-carolina") iso2="us-sc" ;;
    "us-south-dakota") iso2="us-sd" ;;
    "us-tennessee") iso2="us-tn" ;;
    "us-texas") iso2="us-tx" ;;
    "us-utah") iso2="us-ut" ;;
    "us-vermont") iso2="us-vt" ;;
    "us-virginia") iso2="us-va" ;;
    "us-washington") iso2="us-wa" ;;
    "us-west-virginia") iso2="us-wv" ;;
    "us-wisconsin") iso2="us-wi" ;;
    "us-wyoming") iso2="us-wy" ;;
    "ussr") iso2="su" ;;
    "uzbekistan") iso2="uz" ;;
    "vietnam") iso2="vn" ;;
    "wallis-and-futuna") iso2="wf" ;;
    "yemen") iso2="ye" ;;
    *) iso2="" ;;
  esac

  echo "$iso2"
}

find "$folder" -maxdepth 1 -type f -name "*.svg" | while read -r file; do
  filename=$(basename "$file")
  country_name="${filename%.svg}"
  iso2=$(process_file "$country_name")

  if [[ ${#country_name} -eq 2 ]]; then
    continue
  elif [[ "$country_name" =~ ^[[:alpha:]]{2}-[[:alnum:]]{2,3}$ ]]; then
    continue
  fi

  if [ -n "$iso2" ]; then
    cp "$file" "$folder/$iso2.svg"
    #echo "Copied $filename to $iso2.svg"
  else
    echo "No ISO2 mapping for: $country_name" >&2
  fi
done